---
name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run npm build
        run: |
          npm ci
          npm run build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4

      - name: Build and push docker container
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: peavers/terrible-spa
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
